name: "CD Pipeline"

on:
    workflow_run:
        workflows: ["Sample Reacct CI Pipeline / Workflow"]
        types:
            - completed
    workflow_dispatch:        

jobs: 
    deploy:
        runs-on: ubuntu-latest
        environment: production

        steps: 

            - name: "Setup NodeJS"
              uses: actions/setup-node@v4
              with:
                node-version: '21'
            
            - name: "Setup Vercel cli"
              run: npm install -g vercel

            - name: "Download build files"
              uses: actions/download-artifact@v4
              with:
                name: artifact
                run-id: ${{ github.event.workflow_run.id }}
                github-token: ${{ github.token }}

            - name: "Deploy to Vercel"
              run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm 
                
